version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven
      - echo Maven installed
  pre_build:
    commands:
      - echo Checking Docker version...
      - docker version
  build:
    commands:
      - echo Building the JAR...
      - mvn clean package -DskipTests
      - echo Building Docker image...
      - docker build -t springboot-app .
  post_build:
    commands:
      - echo Build complete

artifacts:
  files:
    - appspec.yml
    - scripts/*
    - target/*.jar
    - Dockerfile
